In [1]:
import pandas as pd
import numpy as np

In [2]:
data= pd.read_excel("train.xlsx")

In [3]:
data

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,1048,22,Female,B.Tech,ECE,6.29,0,3,4,6,51,5,1,3,Not Placed
1,37820,20,Female,BCA,ECE,6.05,1,4,6,8,59,8,2,1,Not Placed
2,49668,22,Male,MCA,ME,7.22,1,4,6,6,58,6,2,2,Not Placed
3,19467,22,Male,MCA,ME,7.78,2,4,6,6,90,4,2,0,Placed
4,23094,20,Female,B.Tech,ME,7.63,1,4,6,5,79,6,2,0,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,9362,20,Male,MCA,Civil,7.84,2,5,9,7,68,6,3,1,Placed
44996,8940,19,Female,B.Sc,ME,8.28,1,4,6,5,74,5,2,0,Placed
44997,13097,20,Female,B.Sc,Civil,8.88,0,4,4,5,83,4,2,0,Not Placed
44998,12958,24,Female,MCA,ECE,5.90,1,3,6,6,60,2,2,1,Not Placed
44999,9565,23,Female,B.Tech,ME,6.28,0,4,6,6,64,7,2,3,Not Placed

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            45000 non-null  int64
 1   Age                   45000 non-null  int64
 2   Gender                45000 non-null  object
 3   Degree                45000 non-null  object
 4   Branch                45000 non-null  object
 5   CGPA                  45000 non-null  float64
 6   Internships           45000 non-null  int64
 7   Projects              45000 non-null  int64
 8   Coding_Skills         45000 non-null  int64
 9   Communication_Skills  45000 non-null  int64
 10  Aptitude_Test_Score   45000 non-null  int64
 11  Soft_Skills_Rating    45000 non-null  int64
 12  Certifications        45000 non-null  int64
 13  Backlogs              45000 non-null  int64
 14  Placement_Status      45000 non-null  object
dtypes: float64(1), int64(10), object(4)
memory usage: 5.1+ MB

In [5]:
col= data.columns.tolist()

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
label_encoder= LabelEncoder()

In [9]:
data["Placement_St"]= label_encoder.fit_transform(data["Placement_Status"])

In [11]:
for d_col in col:
    if data[d_col].dtype=="object":
        data.drop(columns=[d_col], inplace=True)

In [15]:
from sklearn.linear_model import Perceptron

In [16]:
p= Perceptron()

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
data

,Student_ID,Age,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_St
0,1048,22,6.29,0,3,4,6,51,5,1,3,0
1,37820,20,6.05,1,4,6,8,59,8,2,1,0
2,49668,22,7.22,1,4,6,6,58,6,2,2,0
3,19467,22,7.78,2,4,6,6,90,4,2,0,1
4,23094,20,7.63,1,4,6,5,79,6,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
44995,9362,20,7.84,2,5,9,7,68,6,3,1,1
44996,8940,19,8.28,1,4,6,5,74,5,2,0,1
44997,13097,20,8.88,0,4,4,5,83,4,2,0,0
44998,12958,24,5.90,1,3,6,6,60,2,2,1,0
44999,9565,23,6.28,0,4,6,6,64,7,2,3,0

In [19]:
x= data.iloc[:,0:11]
y= data.iloc[:,-1]

In [20]:
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
p.fit(x_train,y_train)

Perceptron()

In [23]:
p.coef_

array([[ -22482.  , -153991.  ,   23619.62,   34289.  ,   44171.  ,
          94544.  ,   36682.  ,  309464.  ,  -42333.  ,   34653.  ,
         -80666.  ]])

In [24]:
p.intercept_

array([-7361.])

In [26]:
predictions= p.predict(x_test)

In [ ]:
def model_accuracy(predictions, y_test):
    count=0
    for i in range(len(y_test)):
        if predictions[i]==y_test.iloc[i]:
            count+