In [2]:
import pandas as pd
import numpy as np

In [3]:
data= pd.read_csv("commodities_dataset.csv")

In [4]:
data

,Date,"Crude_Oil_WTI_('Close', 'CL=F')","Crude_Oil_WTI_('High', 'CL=F')","Crude_Oil_WTI_('Low', 'CL=F')","Crude_Oil_WTI_('Open', 'CL=F')","Crude_Oil_WTI_('Volume', 'CL=F')","Crude_Oil_Brent_('Close', 'BZ=F')","Crude_Oil_Brent_('High', 'BZ=F')","Crude_Oil_Brent_('Low', 'BZ=F')","Crude_Oil_Brent_('Open', 'BZ=F')",...,"Lumber_('Close', 'LBS=F')","Lumber_('High', 'LBS=F')","Lumber_('Low', 'LBS=F')","Lumber_('Open', 'LBS=F')","Lumber_('Volume', 'LBS=F')",Year,Month,Quarter,Day_of_Week,Week_of_Year
0,1997-10-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1997,10,4,2,44
1,1997-10-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1997,10,4,3,44
2,1997-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1997,10,4,4,44
3,1997-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1997,11,4,0,45
4,1997-11-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1997,11,4,1,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7098,2025-12-26,56.740002,58.880001,56.650002,58.349998,166669.0,60.639999,62.689999,60.590000,62.349998,...,NaN,NaN,NaN,NaN,NaN,2025,12,4,4,52
7099,2025-12-29,58.080002,58.299999,56.910000,57.040001,178590.0,61.939999,62.150002,60.950001,61.040001,...,NaN,NaN,NaN,NaN,NaN,2025,12,4,0,1
7100,2025-12-30,57.950001,58.470001,57.599998,57.810001,143802.0,61.919998,62.330002,61.509998,61.700001,...,NaN,NaN,NaN,NaN,NaN,2025,12,4,1,1
7101,2025-12-31,57.419998,58.549999,57.200001,57.950001,157160.0,60.849998,61.910000,60.619999,61.270000,...,NaN,NaN,NaN,NaN,NaN,2025,12,4,2,1
7102,2026-01-02,57.320000,57.930000,56.599998,57.410000,166834.0,60.750000,61.360001,60.000000,60.919998,...,NaN,NaN,NaN,NaN,NaN,2026,1,1,4,1

In [5]:
data.describe()

,"Crude_Oil_WTI_('Close', 'CL=F')","Crude_Oil_WTI_('High', 'CL=F')","Crude_Oil_WTI_('Low', 'CL=F')","Crude_Oil_WTI_('Open', 'CL=F')","Crude_Oil_WTI_('Volume', 'CL=F')","Crude_Oil_Brent_('Close', 'BZ=F')","Crude_Oil_Brent_('High', 'BZ=F')","Crude_Oil_Brent_('Low', 'BZ=F')","Crude_Oil_Brent_('Open', 'BZ=F')","Crude_Oil_Brent_('Volume', 'BZ=F')",...,"Lumber_('Close', 'LBS=F')","Lumber_('High', 'LBS=F')","Lumber_('Low', 'LBS=F')","Lumber_('Open', 'LBS=F')","Lumber_('Volume', 'LBS=F')",Year,Month,Quarter,Day_of_Week,Week_of_Year
count,6368.000000,6368.000000,6368.000000,6368.000000,6.368000e+03,4586.000000,4586.000000,4586.000000,4586.000000,4586.000000,...,5723.000000,5723.000000,5723.000000,5723.000000,5723.000000,7103.000000,7103.000000,7103.000000,7103.000000,7103.000000
mean,64.662687,65.668346,63.608268,64.674788,3.025228e+05,78.044446,79.014562,77.022333,78.045000,19786.790449,...,355.762345,361.100541,350.793972,355.940626,423.951774,2011.400817,6.574405,2.523300,2.020414,26.756582
std,24.584397,24.839614,24.286116,24.577595,2.074331e+05,23.801892,23.892890,23.660500,23.782746,17657.899764,...,192.646085,196.393578,188.016720,192.080468,342.595454,8.131989,3.439554,1.117429,1.399704,15.018941
min,-37.630001,13.690000,-40.320000,-14.000000,0.000000e+00,19.330000,21.270000,16.000000,19.559999,0.000000,...,138.100006,142.500000,137.899994,140.000000,0.000000,1997.000000,1.000000,1.000000,0.000000,1.000000
25%,46.317500,47.267500,45.390001,46.279999,1.223942e+05,61.090000,62.102499,60.142500,61.112500,1473.750000,...,251.000000,254.000000,247.800003,251.300003,205.000000,2004.000000,4.000000,2.000000,1.000000,14.000000
50%,63.669998,64.625000,62.849998,63.715000,2.750480e+05,75.465000,76.480003,74.519997,75.494999,20289.000000,...,309.299988,313.700012,306.000000,309.600006,364.000000,2011.000000,7.000000,3.000000,2.000000,27.000000
75%,81.930000,83.082500,80.774998,81.932501,3.898675e+05,97.610001,98.682497,96.495001,97.642502,32252.750000,...,373.700012,378.100006,370.000000,374.000000,568.500000,2018.000000,10.000000,4.000000,3.000000,40.000000
max,145.289993,147.270004,143.220001,145.190002,2.288230e+06,146.080002,147.429993,144.270004,146.080002,175031.000000,...,1686.000000,1711.199951,1652.000000,1677.000000,3798.000000,2026.000000,12.000000,4.000000,4.000000,53.000000

In [6]:
col= data.columns.tolist()

In [7]:
for col_1 in col:
    print(data[col_1].dtype)

object
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
int64
int64
int64
int64
int64

In [9]:
df= data.drop("Date", axis=1)

In [10]:
df.corr()

,"Crude_Oil_WTI_('Close', 'CL=F')","Crude_Oil_WTI_('High', 'CL=F')","Crude_Oil_WTI_('Low', 'CL=F')","Crude_Oil_WTI_('Open', 'CL=F')","Crude_Oil_WTI_('Volume', 'CL=F')","Crude_Oil_Brent_('Close', 'BZ=F')","Crude_Oil_Brent_('High', 'BZ=F')","Crude_Oil_Brent_('Low', 'BZ=F')","Crude_Oil_Brent_('Open', 'BZ=F')","Crude_Oil_Brent_('Volume', 'BZ=F')",...,"Lumber_('Close', 'LBS=F')","Lumber_('High', 'LBS=F')","Lumber_('Low', 'LBS=F')","Lumber_('Open', 'LBS=F')","Lumber_('Volume', 'LBS=F')",Year,Month,Quarter,Day_of_Week,Week_of_Year
"Crude_Oil_WTI_('Close', 'CL=F')",1.000000,0.998711,0.999199,0.997801,0.088759,0.974124,0.973899,0.972153,0.972083,-0.477631,...,0.110585,0.112141,0.111267,0.112599,0.123730,0.323373,-0.013785,-0.011822,0.004798,-0.013535
"Crude_Oil_WTI_('High', 'CL=F')",0.998711,1.000000,0.998175,0.999126,0.096280,0.972697,0.974678,0.971152,0.972911,-0.472687,...,0.112974,0.114616,0.113631,0.115042,0.121045,0.327005,-0.013317,-0.011495,0.002932,-0.013168
"Crude_Oil_WTI_('Low', 'CL=F')",0.999199,0.998175,1.000000,0.998589,0.083192,0.974188,0.974267,0.973806,0.973717,-0.479542,...,0.107244,0.108749,0.108014,0.109266,0.126271,0.321692,-0.012172,-0.010064,0.004695,-0.011841
"Crude_Oil_WTI_('Open', 'CL=F')",0.997801,0.999126,0.998589,1.000000,0.090150,0.972841,0.974798,0.972564,0.974646,-0.475910,...,0.109425,0.111036,0.110147,0.111511,0.123410,0.324794,-0.012127,-0.010026,0.002560,-0.011833
"Crude_Oil_WTI_('Volume', 'CL=F')",0.088759,0.096280,0.083192,0.090150,1.000000,-0.409112,-0.401334,-0.412846,-0.405976,0.473878,...,0.212857,0.212859,0.213750,0.213045,-0.097537,0.555240,-0.065324,-0.062562,0.003081,-0.067508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year,0.323373,0.327005,0.321692,0.324794,0.555240,-0.291243,-0.287374,-0.295019,-0.291542,0.734630,...,0.551980,0.554149,0.551593,0.552997,-0.189707,1.000000,-0.015799,-0.014036,0.003314,-0.016287
Month,-0.013785,-0.013317,-0.012172,-0.012127,-0.065324,-0.038754,-0.038469,-0.037011,-0.036816,-0.038692,...,-0.097099,-0.096509,-0.098633,-0.097652,-0.065994,-0.015799,1.000000,0.971267,-0.015539,0.975602
Quarter,-0.011822,-0.011495,-0.010064,-0.010026,-0.062562,-0.034826,-0.034969,-0.032968,-0.032910,-0.029432,...,-0.103233,-0.102664,-0.104791,-0.103844,-0.062272,-0.014036,0.971267,1.000000,-0.016104,0.950883
Day_of_Week,0.004798,0.002932,0.004695,0.002560,0.003081,0.009378,0.007136,0.009413,0.007376,0.005474,...,0.002902,0.001392,0.002379,0.001104,0.017049,0.003314,-0.015539,-0.016104,1.000000,-0.016428
Week_of_Year,-0.013535,-0.013168,-0.011841,-0.011833,-0.067508,-0.037173,-0.037036,-0.035193,-0.035035,-0.045345,...,-0.098958,-0.098323,-0.100477,-0.099498,-0.051441,-0.016287,0.975602,0.950883,-0.016428,1.000000