In [1]:
import pandas as pd
import numpy as np

In [2]:
data= pd.read_csv("Stock_data.csv")

In [3]:
data

,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,2020-01-01,S&P 500,USA,15607.06,16277.38,15427.47,16057.78,36788921,2.89
1,2020-01-01,NASDAQ Composite,USA,7083.79,7343.64,6461.54,6641.87,22249687,-6.24
2,2020-01-01,Dow Jones,USA,26384.65,26601.25,25659.50,25941.06,4344769,-1.68
3,2020-01-01,FTSE 100,UK,8091.17,8182.45,7617.15,7774.58,44250411,-3.91
4,2020-01-01,Nikkei 225,Japan,1899.43,2044.17,1885.43,1924.21,22498555,1.30
...,...,...,...,...,...,...,...,...,...
18265,2024-12-31,Hang Seng,Hong Kong,1718.84,2027.75,1639.67,2017.82,47658304,17.39
18266,2024-12-31,DAX,Germany,1513.68,1933.41,1485.06,1921.63,13456944,26.95
18267,2024-12-31,CAC 40,France,8944.27,9018.54,8608.51,8737.25,36520735,-2.31
18268,2024-12-31,SSE Composite,China,14674.14,15131.30,14415.31,14888.37,43850831,1.46
18269,2024-12-31,KSE 100,Pakistan,11151.86,11574.65,10995.48,11387.51,15879687,2.11

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18270 entries, 0 to 18269
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  18270 non-null  object
 1   Index_Name            18270 non-null  object
 2   Country               18270 non-null  object
 3   Open                  18270 non-null  float64
 4   High                  18270 non-null  float64
 5   Low                   18270 non-null  float64
 6   Close                 18270 non-null  float64
 7   Volume                18270 non-null  int64
 8   Daily_Change_Percent  18270 non-null  float64
dtypes: float64(5), int64(1), object(3)
memory usage: 1.3+ MB

In [5]:
data["Date"]= pd.to_datetime(data["Date"])

In [6]:
data["Year"]= data["Date"].dt.year.astype("int64")
data["Month"]= data["Date"].dt.month.astype("int64")
data["Day"]= data["Date"].dt.day.astype("int64")

In [7]:
data.drop(columns=["Date"], inplace=True)

In [9]:
col=data.columns.tolist()

In [11]:
for d_col in col:
    if data[d_col].dtype=="object":
        data.drop(columns=[d_col], inplace=True)

In [12]:
data.columns.tolist()

['Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Daily_Change_Percent',
 'Year',
 'Month',
 'Day']

In [13]:
data

,Open,High,Low,Close,Volume,Daily_Change_Percent,Year,Month,Day
0,15607.06,16277.38,15427.47,16057.78,36788921,2.89,2020,1,1
1,7083.79,7343.64,6461.54,6641.87,22249687,-6.24,2020,1,1
2,26384.65,26601.25,25659.50,25941.06,4344769,-1.68,2020,1,1
3,8091.17,8182.45,7617.15,7774.58,44250411,-3.91,2020,1,1
4,1899.43,2044.17,1885.43,1924.21,22498555,1.30,2020,1,1
...,...,...,...,...,...,...,...,...,...
18265,1718.84,2027.75,1639.67,2017.82,47658304,17.39,2024,12,31
18266,1513.68,1933.41,1485.06,1921.63,13456944,26.95,2024,12,31
18267,8944.27,9018.54,8608.51,8737.25,36520735,-2.31,2024,12,31
18268,14674.14,15131.30,14415.31,14888.37,43850831,1.46,2024,12,31
18269,11151.86,11574.65,10995.48,11387.51,15879687,2.11,2024,12,31

In [14]:
data["Daily_Percent"]= data["Daily_Change_Percent"].copy()

In [16]:
data.drop(columns=["Daily_Change_Percent"], inplace=True)

In [18]:
x= data.iloc[:,0:8]
y= data.iloc[:,-1]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
from sklearn.linear_model import Perceptron

In [25]:
x_train, x_test,_train, y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
p= Perceptron()

In [27]:
p.fit(x_train, y_train)

ValueError: y should be a 1d array, got an array of shape (3654, 8) instead.